import type { Question } from '../question.entity';

export type FoundationQuestionSeed = Pick<
  Question,
  | 'question_id'
  | 'subject'
  | 'chapter'
  | 'topic'
  | 'subtopic'
  | 'question_text'
  | 'options'
  | 'correct_answer'
  | 'solution'
  | 'bloom_level'
  | 'difficulty'
  | 'marks'
  | 'estimated_time_sec'
  | 'concept_tags'
  | 'common_errors'
  | 'quality_score'
>;

const PHYSICS = 'Physics';
const CHARGES_CHAPTER = 'Electric Charges and Fields';
const POTENTIAL_CHAPTER = 'Electrostatic Potential and Capacitance';

function makeQuestion(
  questionId: string,
  chapter: string,
  topic: string,
  difficulty: 'Easy' | 'Medium' | 'Hard',
  bloomLevel: 'Remember' | 'Understand' | 'Apply' | 'Analyze' | 'Evaluate',
  questionText: string,
  options: string[],
  correctAnswer: string,
  solution: string,
  conceptTags: string[],
  commonErrors: string[],
  qualityScore = 92,
): FoundationQuestionSeed {
  return {
    question_id: questionId,
    subject: PHYSICS,
    chapter,
    topic,
    subtopic: null,
    question_text: questionText,
    options,
    correct_answer: correctAnswer,
    solution,
    bloom_level: bloomLevel,
    difficulty,
    marks: 4,
    estimated_time_sec:
      difficulty === 'Hard' ? 150 : difficulty === 'Medium' ? 90 : 60,
    concept_tags: conceptTags,
    common_errors: commonErrors,
    quality_score: qualityScore,
  };
}

export const FOUNDATION_QUESTION_BANK: FoundationQuestionSeed[] = [
  makeQuestion(
    'PHY-FND-CL-01',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Easy',
    'Remember',
    'What is the SI unit of electric charge?',
    ['Ampere', 'Coulomb', 'Volt', 'Farad'],
    'Coulomb',
    'Electric charge is measured in coulomb (C) in the SI system.',
    ['electric charge', 'SI units'],
    ['Confusing electric charge with current or potential'],
  ),
  makeQuestion(
    'PHY-FND-CL-02',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Easy',
    'Understand',
    'Two isolated point charges have the same sign. Their electrostatic interaction is:',
    ['Attractive', 'Repulsive', 'Always zero', 'Gravitational only'],
    'Repulsive',
    'Like charges repel and unlike charges attract.',
    ['charge interaction', 'sign of charge'],
    ['Reversing the interaction of like and unlike charges'],
  ),
  makeQuestion(
    'PHY-FND-CL-03',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Easy',
    'Understand',
    'Which expression gives the magnitude of force between two point charges q1 and q2 separated by distance r in vacuum?',
    ['k|q1q2|/r^2', 'k|q1q2|/r', 'k|q1+q2|/r^2', 'kr^2/|q1q2|'],
    'k|q1q2|/r^2',
    'Coulomb law states that force is k times the product of charge magnitudes divided by the square of their separation.',
    ["Coulomb's law", 'inverse square law'],
    ['Forgetting to square the separation'],
  ),
  makeQuestion(
    'PHY-FND-CL-04',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Easy',
    'Apply',
    'Two charges of 1 microC each are 3 m apart in vacuum. Take k = 9 x 10^9. What is the force magnitude?',
    ['1 x 10^-3 N', '1 x 10^-2 N', '3 x 10^-3 N', '9 x 10^-3 N'],
    '1 x 10^-3 N',
    'F = 9 x 10^9 x 10^-6 x 10^-6 / 3^2 = 1 x 10^-3 N.',
    ["Coulomb's law", 'substitution'],
    ['Using 3 instead of 3^2 in the denominator'],
  ),
  makeQuestion(
    'PHY-FND-CL-05',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Easy',
    'Apply',
    'If the separation between two fixed point charges is doubled, their electrostatic force becomes:',
    ['Four times', 'Twice', 'One half', 'One fourth'],
    'One fourth',
    'Force is inversely proportional to r^2, so replacing r by 2r makes the force one fourth.',
    ['inverse square law', 'distance scaling'],
    ['Applying an inverse rather than inverse-square relationship'],
  ),
  makeQuestion(
    'PHY-FND-CL-06',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Medium',
    'Analyze',
    'For fixed separation, q1 is doubled and q2 is unchanged. The electrostatic force changes by what factor?',
    ['1/2', '1', '2', '4'],
    '2',
    'Coulomb force is proportional to q1q2. Doubling one charge doubles the force.',
    ['charge scaling', "Coulomb's law"],
    ['Doubling both charges mentally instead of only one'],
  ),
  makeQuestion(
    'PHY-FND-CL-07',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Medium',
    'Apply',
    'Two identical positive charges are fixed 2 m apart. A positive test charge is placed exactly midway. What is the net electrostatic force on the test charge?',
    ['Zero', 'Toward the left charge', 'Toward the right charge', 'Perpendicular to the line joining charges'],
    'Zero',
    'The two forces have equal magnitude and opposite directions at the midpoint, so they cancel.',
    ['superposition', 'symmetry'],
    ['Adding equal opposite force magnitudes as scalars'],
  ),
  makeQuestion(
    'PHY-FND-CL-08',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Medium',
    'Apply',
    'A force F acts between charges q and Q separated by d. What is the new force if q becomes 2q and separation becomes 3d?',
    ['2F/3', '2F/9', '3F/2', '9F/2'],
    '2F/9',
    'The force scales as charge divided by distance squared: Fprime/F = 2/3^2 = 2/9.',
    ['scaling laws', "Coulomb's law"],
    ['Forgetting to square the changed distance'],
  ),
  makeQuestion(
    'PHY-FND-CL-09',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Medium',
    'Evaluate',
    'Which statement is correct for charges +q and -q separated by distance r?',
    ['They repel with force kq^2/r^2', 'They attract with force kq^2/r^2', 'They exert no force because total charge is zero', 'They attract with force kq/r'],
    'They attract with force kq^2/r^2',
    'The signs determine attraction, while the magnitude comes from k times the product of charge magnitudes divided by r^2.',
    ['attraction', "Coulomb's law"],
    ['Treating zero net charge as zero interaction'],
  ),
  makeQuestion(
    'PHY-FND-CL-10',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Medium',
    'Analyze',
    'By what factor must separation be changed to reduce Coulomb force to one sixteenth while charges remain fixed?',
    ['2', '4', '8', '16'],
    '4',
    'Since F is proportional to 1/r^2, making r four times larger makes F one sixteenth.',
    ['inverse square law', 'proportional reasoning'],
    ['Using a factor of sixteen directly for distance'],
  ),
  makeQuestion(
    'PHY-FND-CL-11',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Hard',
    'Apply',
    'Three equal positive charges occupy the vertices of an equilateral triangle. If each of the two forces on one vertex has magnitude F, the resultant force magnitude is:',
    ['F', 'sqrt(2) F', 'sqrt(3) F', '2F'],
    'sqrt(3) F',
    'The two equal forces meet at 60 degrees, so resultant = sqrt(F^2 + F^2 + 2F^2 cos 60 degrees) = sqrt(3) F.',
    ['vector addition', 'equilateral symmetry'],
    ['Adding force magnitudes without accounting for the angle'],
    95,
  ),
  makeQuestion(
    'PHY-FND-CL-12',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Hard',
    'Analyze',
    'Charges +Q and +4Q are separated by distance d. On the line between them, where is the electric field zero?',
    ['d/5 from +Q', 'd/3 from +Q', 'd/2 from +Q', '2d/3 from +Q'],
    'd/3 from +Q',
    'Set Q/x^2 = 4Q/(d-x)^2. This gives d-x = 2x, hence x = d/3 from the smaller charge.',
    ['field cancellation', 'inverse square law'],
    ['Placing the zero-field point nearer the larger charge'],
    96,
  ),
  makeQuestion(
    'PHY-FND-CL-13',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Hard',
    'Analyze',
    'Four equal positive charges are fixed at the corners of a square. What is the electric force on a positive test charge placed at the centre?',
    ['Zero', 'Toward one corner', 'Along a diagonal away from the nearest charge', 'Infinite'],
    'Zero',
    'The electric field contributions cancel pairwise by square symmetry, so the force on any test charge at the centre is zero.',
    ['superposition', 'square symmetry'],
    ['Considering only the nearest corner charges'],
    94,
  ),
  makeQuestion(
    'PHY-FND-CL-14',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Hard',
    'Apply',
    'What is the force magnitude between charges 4 microC and 1 microC separated by 0.2 m in vacuum? Take k = 9 x 10^9.',
    ['0.09 N', '0.9 N', '9 N', '90 N'],
    '0.9 N',
    'F = 9 x 10^9 x 4 x 10^-12 / 0.2^2 = 0.9 N.',
    ["Coulomb's law", 'scientific notation'],
    ['Misplacing the decimal when squaring 0.2'],
    94,
  ),
  makeQuestion(
    'PHY-FND-CL-15',
    CHARGES_CHAPTER,
    "Coulomb's Law and Charge",
    'Hard',
    'Evaluate',
    'Two electrostatic forces of magnitudes F and 3F act at right angles on a particle. Which is the correct resultant magnitude?',
    ['2F', 'sqrt(5) F', 'sqrt(10) F', '4F'],
    'sqrt(10) F',
    'Perpendicular vector addition gives R = sqrt(F^2 + (3F)^2) = sqrt(10) F.',
    ['vector addition', 'resultant force'],
    ['Adding perpendicular force magnitudes directly'],
    93,
  ),

  makeQuestion(
    'PHY-FND-EF-01',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Easy',
    'Remember',
    'Which is an SI unit of electric field intensity?',
    ['N/C', 'C/N', 'J/C', 'C m'],
    'N/C',
    'Electric field is force per unit positive test charge, so its SI unit is newton per coulomb.',
    ['electric field', 'SI units'],
    ['Confusing field with electric potential'],
  ),
  makeQuestion(
    'PHY-FND-EF-02',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Easy',
    'Understand',
    'The electric field due to an isolated positive point charge is directed:',
    ['Toward the charge', 'Away from the charge', 'In closed circles', 'Perpendicular to every radial line'],
    'Away from the charge',
    'A positive test charge would be repelled, so field arrows point radially outward.',
    ['field direction', 'positive charge'],
    ['Reversing field direction for a positive source'],
  ),
  makeQuestion(
    'PHY-FND-EF-03',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Easy',
    'Apply',
    'A force of 6 N acts on a +2 C test charge. What is the electric field magnitude at that point?',
    ['3 N/C', '4 N/C', '8 N/C', '12 N/C'],
    '3 N/C',
    'E = F/q = 6/2 = 3 N/C.',
    ['electric field', 'E=F/q'],
    ['Multiplying F by q instead of dividing'],
  ),
  makeQuestion(
    'PHY-FND-EF-04',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Easy',
    'Apply',
    'What is the field magnitude 3 m from a +2 microC point charge in vacuum? Take k = 9 x 10^9.',
    ['200 N/C', '2000 N/C', '6000 N/C', '18000 N/C'],
    '2000 N/C',
    'E = kq/r^2 = 9 x 10^9 x 2 x 10^-6 / 9 = 2000 N/C.',
    ['point charge field', 'substitution'],
    ['Using potential formula kq/r'],
  ),
  makeQuestion(
    'PHY-FND-EF-05',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Easy',
    'Understand',
    'For a uniform electric field E perpendicular to a flat surface of area A, the flux through the surface is:',
    ['EA', 'E/A', 'E+A', 'Zero'],
    'EA',
    'Electric flux is EA cos theta. For a field along the surface normal, theta is zero and flux is EA.',
    ['electric flux', 'surface normal'],
    ['Using the angle with the plane instead of its normal'],
  ),
  makeQuestion(
    'PHY-FND-EF-06',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Medium',
    'Analyze',
    'Two equal positive charges are placed symmetrically about point P. What is the electric field at P if P is their midpoint?',
    ['Zero', 'Toward the left charge', 'Toward the right charge', 'Perpendicular to their line'],
    'Zero',
    'At the midpoint, the two equal fields point in opposite directions and cancel.',
    ['superposition', 'symmetry'],
    ['Adding equal field magnitudes without direction'],
  ),
  makeQuestion(
    'PHY-FND-EF-07',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Medium',
    'Apply',
    'A negative test charge is placed in an electric field directed east. The force on the charge is directed:',
    ['East', 'West', 'North', 'Zero'],
    'West',
    'The field direction is defined for a positive test charge. A negative charge experiences force opposite to the field.',
    ['force in electric field', 'sign of test charge'],
    ['Using the positive-charge force direction for a negative charge'],
  ),
  makeQuestion(
    'PHY-FND-EF-08',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Medium',
    'Apply',
    'At a point 2 m from a point charge, field magnitude is E. What is the field magnitude at 4 m from the same charge?',
    ['E/4', 'E/2', '2E', '4E'],
    'E/4',
    'Point-charge field varies as 1/r^2. Doubling distance reduces field to one fourth.',
    ['inverse square law', 'point charge field'],
    ['Using inverse-distance rather than inverse-square scaling'],
  ),
  makeQuestion(
    'PHY-FND-EF-09',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Medium',
    'Understand',
    'According to Gauss law, the net electric flux through any closed surface enclosing charge q is:',
    ['q/epsilon_0', 'q/(2 epsilon_0)', 'epsilon_0/q', 'Zero for every closed surface'],
    'q/epsilon_0',
    'Gauss law states that total outward flux through a closed surface equals enclosed charge divided by epsilon_0.',
    ["Gauss's law", 'electric flux'],
    ['Using area or surface shape in the total-flux result'],
  ),
  makeQuestion(
    'PHY-FND-EF-10',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Medium',
    'Apply',
    'For a conductor in electrostatic equilibrium with surface charge density sigma, the field just outside its surface is:',
    ['sigma/(2 epsilon_0)', 'sigma/epsilon_0', 'zero', '2 sigma/epsilon_0'],
    'sigma/epsilon_0',
    'A pillbox Gaussian surface across a conductor surface gives E = sigma/epsilon_0 just outside and zero inside.',
    ['conductors', "Gauss's law"],
    ['Using the infinite non-conducting sheet result sigma/(2 epsilon_0)'],
  ),
  makeQuestion(
    'PHY-FND-EF-11',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Hard',
    'Apply',
    'At a distant point on the axial line of a short electric dipole of moment p, the field magnitude is approximately:',
    ['kp/r^3', '2kp/r^3', 'kq/r^2', '2kq/r^2'],
    '2kp/r^3',
    'For a short dipole at a far axial point, E axial = 2kp/r^3.',
    ['electric dipole', 'axial field'],
    ['Using the equatorial dipole-field magnitude'],
    95,
  ),
  makeQuestion(
    'PHY-FND-EF-12',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Hard',
    'Apply',
    'A uniformly charged ring of radius a and charge Q produces field at point x on its axis equal to:',
    ['kQ/x^2', 'kQx/(x^2+a^2)^(3/2)', 'kQ/(x^2+a^2)', 'kQa/(x^2+a^2)^(3/2)'],
    'kQx/(x^2+a^2)^(3/2)',
    'Transverse field components cancel by symmetry; axial components add to kQx/(x^2+a^2)^(3/2).',
    ['charged ring', 'symmetry'],
    ['Forgetting the axial x factor'],
    96,
  ),
  makeQuestion(
    'PHY-FND-EF-13',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Hard',
    'Apply',
    'The electric field magnitude on either side of an infinite non-conducting plane sheet with surface charge density sigma is:',
    ['sigma/(2 epsilon_0)', 'sigma/epsilon_0', 'zero', '2 sigma/epsilon_0'],
    'sigma/(2 epsilon_0)',
    'A Gaussian pillbox has equal flux through two faces, giving 2EA = sigma A/epsilon_0.',
    ['infinite sheet', "Gauss's law"],
    ['Using the field immediately outside a conductor'],
    95,
  ),
  makeQuestion(
    'PHY-FND-EF-14',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Hard',
    'Analyze',
    'A charge q is at the centre of a cube. What is the flux through one face of the cube?',
    ['q/epsilon_0', 'q/(2 epsilon_0)', 'q/(4 epsilon_0)', 'q/(6 epsilon_0)'],
    'q/(6 epsilon_0)',
    'The total flux is q/epsilon_0. Cube symmetry divides that equally among six faces.',
    ["Gauss's law", 'symmetry'],
    ['Assigning the total closed-surface flux to one face'],
    95,
  ),
  makeQuestion(
    'PHY-FND-EF-15',
    CHARGES_CHAPTER,
    "Electric Field and Gauss's Law",
    'Hard',
    'Evaluate',
    'A charged conducting sphere is in electrostatic equilibrium. Which statement is correct inside the conducting material?',
    ['Electric field is zero', 'Electric field is uniform and non-zero', 'Potential must be zero', 'Charge density is always zero'],
    'Electric field is zero',
    'Free charges move until the electric field inside the conducting material vanishes. The potential is constant but need not be zero.',
    ['conductors', 'electrostatic equilibrium'],
    ['Confusing constant potential with zero potential'],
    94,
  ),

  makeQuestion(
    'PHY-FND-PC-01',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Easy',
    'Remember',
    'What is the SI unit of electric potential?',
    ['Volt', 'Coulomb', 'Tesla', 'Weber'],
    'Volt',
    'Electric potential is energy per unit charge and is measured in volt (V).',
    ['electric potential', 'SI units'],
    ['Confusing potential with charge'],
  ),
  makeQuestion(
    'PHY-FND-PC-02',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Easy',
    'Understand',
    'The work done in moving a test charge between two points on the same equipotential surface is:',
    ['Zero', 'Always positive', 'Always negative', 'Dependent only on mass'],
    'Zero',
    'Potential difference on an equipotential surface is zero, so W = q deltaV is zero.',
    ['equipotential surface', 'work done'],
    ['Using path length rather than potential difference'],
  ),
  makeQuestion(
    'PHY-FND-PC-03',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Easy',
    'Understand',
    'The capacitance C of an isolated conductor is defined by:',
    ['Q/V', 'V/Q', 'QV', 'Q^2/V'],
    'Q/V',
    'Capacitance is charge stored per unit potential difference: C = Q/V.',
    ['capacitance', 'definition'],
    ['Inverting the capacitance ratio'],
  ),
  makeQuestion(
    'PHY-FND-PC-04',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Easy',
    'Apply',
    'A 6 microF capacitor is connected across 12 V. What charge is stored?',
    ['0.5 microC', '18 microC', '72 microC', '144 microC'],
    '72 microC',
    'Q = CV = 6 microF x 12 V = 72 microC.',
    ['capacitance', 'Q=CV'],
    ['Dividing voltage by capacitance'],
  ),
  makeQuestion(
    'PHY-FND-PC-05',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Easy',
    'Apply',
    'What is the energy stored in a 2 microF capacitor charged to 10 V?',
    ['10 microJ', '50 microJ', '100 microJ', '200 microJ'],
    '100 microJ',
    'U = one half CV^2 = one half x 2 microF x 10^2 = 100 microJ.',
    ['capacitor energy', 'U=1/2CV^2'],
    ['Omitting the one-half factor'],
  ),
  makeQuestion(
    'PHY-FND-PC-06',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Medium',
    'Apply',
    'What is the potential 9 m from a +2 microC point charge in vacuum? Take k = 9 x 10^9.',
    ['200 V', '2000 V', '6000 V', '18000 V'],
    '2000 V',
    'V = kq/r = 9 x 10^9 x 2 x 10^-6 / 9 = 2000 V.',
    ['point charge potential', 'V=kq/r'],
    ['Using r^2 as in the field formula'],
  ),
  makeQuestion(
    'PHY-FND-PC-07',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Medium',
    'Apply',
    'Capacitors of 3 microF and 6 microF are connected in parallel. Their equivalent capacitance is:',
    ['2 microF', '3 microF', '6 microF', '9 microF'],
    '9 microF',
    'Parallel capacitors add directly: Ceq = 3 + 6 = 9 microF.',
    ['capacitors in parallel', 'equivalent capacitance'],
    ['Applying the series formula to a parallel circuit'],
  ),
  makeQuestion(
    'PHY-FND-PC-08',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Medium',
    'Understand',
    'If a dielectric of constant K completely fills a parallel-plate capacitor, its capacitance becomes:',
    ['C/K', 'KC', 'C+K', 'Unchanged'],
    'KC',
    'A dielectric reduces effective electric field and raises capacitance by factor K.',
    ['dielectric', 'capacitance'],
    ['Assuming dielectric reduces capacitance'],
  ),
  makeQuestion(
    'PHY-FND-PC-09',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Medium',
    'Analyze',
    'Capacitors of 3 microF and 6 microF are in series across 18 V. What is the voltage across the 3 microF capacitor?',
    ['3 V', '6 V', '9 V', '12 V'],
    '12 V',
    'Series equivalent is 2 microF, so Q = 36 microC. Voltage across 3 microF is Q/C = 12 V.',
    ['capacitors in series', 'potential division'],
    ['Dividing voltage equally despite unequal capacitances'],
  ),
  makeQuestion(
    'PHY-FND-PC-10',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Medium',
    'Understand',
    'In the direction of an electric field, electric potential:',
    ['Increases', 'Decreases', 'Remains zero', 'Becomes infinite'],
    'Decreases',
    'Electric field points in the direction of the steepest decrease of electric potential: E = -dV/dr.',
    ['electric potential', 'electric field relation'],
    ['Dropping the negative sign in E = -grad V'],
  ),
  makeQuestion(
    'PHY-FND-PC-11',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Hard',
    'Analyze',
    'A charged capacitor is disconnected from its battery. A dielectric of constant K is then inserted fully. Its potential difference becomes:',
    ['KV', 'V/K', 'V', 'K^2V'],
    'V/K',
    'After disconnection Q stays constant while capacitance becomes KC. Since V = Q/C, voltage becomes V/K.',
    ['dielectric', 'isolated capacitor'],
    ['Assuming voltage remains fixed after the battery is removed'],
    95,
  ),
  makeQuestion(
    'PHY-FND-PC-12',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Hard',
    'Analyze',
    'A capacitor remains connected to an ideal battery while a dielectric of constant K is inserted fully. Its stored energy becomes:',
    ['U/K', 'U', 'KU', 'K^2U'],
    'KU',
    'Battery keeps V constant and C becomes KC. With U = one half CV^2, energy becomes KU.',
    ['dielectric', 'capacitor energy'],
    ['Using the disconnected-capacitor result while the battery remains connected'],
    96,
  ),
  makeQuestion(
    'PHY-FND-PC-13',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Hard',
    'Apply',
    'What is the equivalent capacitance of 2 microF and 3 microF capacitors in series?',
    ['1.2 microF', '2.5 microF', '5 microF', '6 microF'],
    '1.2 microF',
    'For series connection, 1/Ceq = 1/2 + 1/3 = 5/6, so Ceq = 6/5 = 1.2 microF.',
    ['capacitors in series', 'reciprocal addition'],
    ['Adding series capacitances directly'],
    94,
  ),
  makeQuestion(
    'PHY-FND-PC-14',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Hard',
    'Analyze',
    'A charged parallel-plate capacitor is disconnected from its source. Plate separation is doubled without changing plate area. Its stored energy becomes:',
    ['U/2', 'U', '2U', '4U'],
    '2U',
    'Disconnection keeps Q constant. Doubling separation halves C, and U = Q^2/(2C), so energy doubles.',
    ['isolated capacitor', 'energy scaling'],
    ['Using U = one half CV^2 while assuming voltage is fixed'],
    96,
  ),
  makeQuestion(
    'PHY-FND-PC-15',
    POTENTIAL_CHAPTER,
    'Electric Potential and Capacitance',
    'Hard',
    'Evaluate',
    'A conducting sphere of radius R carries charge Q. Its electric potential at the surface is:',
    ['kQ/R', 'kQ/R^2', 'kQR', 'zero'],
    'kQ/R',
    'Outside a charged conducting sphere, potential is the same as that of a point charge Q at the centre. At r = R, V = kQ/R.',
    ['conducting sphere', 'electric potential'],
    ['Using the electric-field expression kQ/R^2 for potential'],
    94,
  ),
];
