import type { CompassChapter } from '../../catalog/chapter-meta.types';

/**
 * Chapter study-guide data adapted from the jee-compass project
 * (CBSE Class 12 PCM). Only descriptive fields are kept: its CBSE board
 * "exam weight" and hand-typed question counts are intentionally dropped,
 * as they do not apply to JEE and go stale. Generated once from the source
 * files by text extraction (never by executing them) and reviewed here.
 */
export const COMPASS_CHAPTERS: readonly CompassChapter[] = [
  {
    subjectId: 'physics',
    chapterId: 1,
    name: 'Electric Charges and Fields',
    unit: 'Electrostatics',
    topics: [
      "Coulomb's Law",
      'Electric Field',
      'Electric Dipole',
      "Gauss's Law",
      'Field Lines',
      'Conductors & Insulators',
    ],
    overview:
      "Introduces the concept of electric charge, Coulomb's law, and the electric field produced by point charges and continuous distributions. Gauss's law simplifies field calculations for symmetric charge distributions.",
    objectives: [
      "State and apply Coulomb's law for point charges",
      'Calculate electric field due to dipoles and continuous distributions',
      "Apply Gauss's law to find fields for symmetric geometries",
      'Distinguish between conductors and insulators in electrostatic equilibrium',
    ],
    keyFormulas: ['F = kq₁q₂/r²', 'E = F/q₀', 'Φ = q/ε₀'],
    difficulty: 'Medium',
    studyTimeMinutes: 90,
  },
  {
    subjectId: 'physics',
    chapterId: 2,
    name: 'Electrostatic Potential and Capacitance',
    unit: 'Electrostatics',
    topics: [
      'Electric Potential',
      'Equipotential Surfaces',
      'Capacitance',
      'Energy Stored',
      'Dielectrics',
      'Parallel Plate Capacitor',
    ],
    overview:
      'Covers electric potential, potential energy, and capacitance. Explores how dielectrics affect capacitors and how energy is stored in electric fields.',
    objectives: [
      'Define and calculate electric potential and potential difference',
      'Derive capacitance of parallel plate and spherical capacitors',
      'Explain the effect of dielectrics on capacitance',
      'Calculate energy stored in a capacitor',
    ],
    keyFormulas: ['V = kq/r', 'C = ε₀A/d', 'U = ½CV²'],
    difficulty: 'Medium',
    studyTimeMinutes: 85,
  },
  {
    subjectId: 'physics',
    chapterId: 3,
    name: 'Current Electricity',
    unit: 'Current',
    topics: [
      "Ohm's Law",
      "Kirchhoff's Laws",
      'Wheatstone Bridge',
      'Potentiometer',
      'EMF & Internal Resistance',
      'Drift Velocity',
    ],
    overview:
      "Studies the flow of electric charge through conductors. Covers Ohm's law, resistivity, Kirchhoff's laws, and measuring instruments like the Wheatstone bridge and potentiometer.",
    objectives: [
      "Apply Ohm's law and understand its limitations",
      "Use Kirchhoff's current and voltage laws to solve circuits",
      'Explain the working of Wheatstone bridge and potentiometer',
      'Derive expressions for drift velocity and mobility',
    ],
    keyFormulas: ['V = IR', 'R = ρl/A', 'P = I²R'],
    difficulty: 'Hard',
    studyTimeMinutes: 100,
  },
  {
    subjectId: 'physics',
    chapterId: 4,
    name: 'Moving Charges and Magnetism',
    unit: 'Magnetism',
    topics: [
      'Biot-Savart Law',
      "Ampere's Law",
      'Lorentz Force',
      'Cyclotron',
      'Solenoid',
      'Galvanometer',
    ],
    overview:
      "Explores the magnetic effects of electric current. Covers Biot-Savart law, Ampere's circuital law, force on current-carrying conductors, and the cyclotron.",
    objectives: [
      'Apply Biot-Savart law to calculate magnetic fields',
      "Use Ampere's law for solenoids and toroids",
      'Analyse motion of charged particles in magnetic fields',
      'Explain the principle of a cyclotron',
    ],
    keyFormulas: ['dB = μ₀Idl×r̂/4πr²', 'F = qv×B', 'B = μ₀nI'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'physics',
    chapterId: 5,
    name: 'Magnetism and Matter',
    unit: 'Magnetism',
    topics: [
      'Bar Magnet',
      'Magnetic Field Lines',
      "Earth's Magnetism",
      'Diamagnetism',
      'Paramagnetism',
      'Ferromagnetism',
    ],
    overview:
      "Examines the magnetic properties of materials including diamagnetic, paramagnetic, and ferromagnetic substances. Covers Earth's magnetism and the bar magnet as a magnetic dipole.",
    objectives: [
      'Compare diamagnetic, paramagnetic, and ferromagnetic materials',
      "Explain Earth's magnetic field and its elements",
      'Relate bar magnet properties to magnetic dipole moment',
      'Define magnetic susceptibility and permeability',
    ],
    keyFormulas: ['M = m×2l', 'B = μ₀μᵣH', 'χ = M/H'],
    difficulty: 'Easy',
    studyTimeMinutes: 60,
  },
  {
    subjectId: 'physics',
    chapterId: 6,
    name: 'Electromagnetic Induction',
    unit: 'EMI & AC',
    topics: [
      "Faraday's Law",
      "Lenz's Law",
      'Mutual Inductance',
      'Self Inductance',
      'Eddy Currents',
      'Motional EMF',
    ],
    overview:
      "Covers Faraday's laws of electromagnetic induction, Lenz's law, self and mutual inductance, and eddy currents. Foundation for understanding AC circuits and transformers.",
    objectives: [
      "State and apply Faraday's laws of electromagnetic induction",
      "Apply Lenz's law to determine direction of induced current",
      'Calculate self and mutual inductance of coils',
      'Explain eddy currents and their applications',
    ],
    keyFormulas: ['ε = -dΦ/dt', 'L = NΦ/I', 'M = μ₀N₁N₂A/l'],
    difficulty: 'Hard',
    studyTimeMinutes: 90,
  },
  {
    subjectId: 'physics',
    chapterId: 7,
    name: 'Alternating Current',
    unit: 'EMI & AC',
    topics: [
      'AC Generator',
      'RMS Values',
      'LCR Circuit',
      'Resonance',
      'Transformer',
      'Power Factor',
    ],
    overview:
      'Studies alternating current circuits including resistors, inductors, and capacitors. Covers resonance in LCR circuits, power factor, and the working of transformers.',
    objectives: [
      'Analyse AC circuits with R, L, and C components',
      'Derive resonance condition for LCR series circuit',
      'Calculate power in AC circuits and power factor',
      'Explain the working principle of a transformer',
    ],
    keyFormulas: ['Z = √(R²+(XL-XC)²)', 'f₀ = 1/2π√LC', 'P = VrmsIrmscosφ'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'physics',
    chapterId: 8,
    name: 'Electromagnetic Waves',
    unit: 'EM Waves',
    topics: [
      "Maxwell's Equations",
      'Displacement Current',
      'EM Spectrum',
      'Properties of EM Waves',
      'Infrared',
      'UV Rays',
    ],
    overview:
      "Introduces Maxwell's equations and the concept of displacement current. Covers the nature, properties, and spectrum of electromagnetic waves.",
    objectives: [
      "Explain Maxwell's modification of Ampere's law",
      'Describe the nature and properties of EM waves',
      'Identify different regions of the electromagnetic spectrum',
      'Explain the significance of displacement current',
    ],
    keyFormulas: ['c = 1/√μ₀ε₀', 'c = νλ', 'E₀/B₀ = c'],
    difficulty: 'Easy',
    studyTimeMinutes: 55,
  },
  {
    subjectId: 'physics',
    chapterId: 9,
    name: 'Ray Optics and Optical Instruments',
    unit: 'Optics',
    topics: [
      'Reflection',
      'Refraction',
      'Total Internal Reflection',
      'Lens Formula',
      'Microscope',
      'Telescope',
    ],
    overview:
      'Covers reflection, refraction, total internal reflection, and the lens and mirror formulae. Explains the working of optical instruments like microscopes and telescopes.',
    objectives: [
      'Apply mirror and lens formulae to solve problems',
      'Explain total internal reflection and its applications',
      'Derive magnification for microscopes and telescopes',
      'Understand dispersion of light through prisms',
    ],
    keyFormulas: ['1/f = 1/v - 1/u', 'n = sin i/sin r', 'P = 1/f(m)'],
    difficulty: 'Hard',
    studyTimeMinutes: 110,
  },
  {
    subjectId: 'physics',
    chapterId: 10,
    name: 'Wave Optics',
    unit: 'Optics',
    topics: [
      'Huygens Principle',
      'Interference',
      'YDSE',
      'Diffraction',
      'Polarisation',
      "Brewster's Law",
    ],
    overview:
      "Explores the wave nature of light through Huygens' principle, interference (Young's double slit), diffraction, and polarisation.",
    objectives: [
      "Apply Huygens' principle to explain reflection and refraction",
      'Derive conditions for constructive and destructive interference',
      'Explain diffraction patterns from single slits',
      "Describe polarisation by reflection and Brewster's law",
    ],
    keyFormulas: ['β = λD/d', '2d sinθ = nλ', 'tan iB = n'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'physics',
    chapterId: 11,
    name: 'Dual Nature of Radiation and Matter',
    unit: 'Modern Physics',
    topics: [
      'Photoelectric Effect',
      "Einstein's Equation",
      'de Broglie Wavelength',
      'Davisson-Germer',
      'Work Function',
    ],
    overview:
      "Covers the photoelectric effect, Einstein's photoelectric equation, and the wave-particle duality of matter through de Broglie's hypothesis.",
    objectives: [
      'Explain the photoelectric effect and its observations',
      "Apply Einstein's photoelectric equation",
      'Calculate de Broglie wavelength of particles',
      'Describe the Davisson-Germer experiment',
    ],
    keyFormulas: ['KE = hν - φ', 'λ = h/mv', 'eV₀ = hν - φ'],
    difficulty: 'Medium',
    studyTimeMinutes: 75,
  },
  {
    subjectId: 'physics',
    chapterId: 12,
    name: 'Atoms',
    unit: 'Modern Physics',
    topics: [
      'Rutherford Model',
      'Bohr Model',
      'Hydrogen Spectrum',
      'Energy Levels',
      'Atomic Spectra',
    ],
    overview:
      "Studies atomic models from Thomson to Bohr. Covers Bohr's postulates, hydrogen spectrum, and energy levels of the hydrogen atom.",
    objectives: [
      'Compare Thomson, Rutherford, and Bohr atomic models',
      "Apply Bohr's postulates to calculate energy levels",
      'Explain the origin of hydrogen spectral series',
      'Calculate radius and velocity of electron in Bohr orbits',
    ],
    keyFormulas: ['Eₙ = -13.6/n² eV', 'rₙ = n²a₀', '1/λ = R(1/n₁²-1/n₂²)'],
    difficulty: 'Medium',
    studyTimeMinutes: 70,
  },
  {
    subjectId: 'physics',
    chapterId: 13,
    name: 'Nuclei',
    unit: 'Modern Physics',
    topics: [
      'Nuclear Binding Energy',
      'Radioactivity',
      'Alpha Decay',
      'Beta Decay',
      'Nuclear Fission',
      'Nuclear Fusion',
    ],
    overview:
      'Covers nuclear structure, binding energy, radioactive decay laws, and nuclear reactions including fission and fusion.',
    objectives: [
      'Calculate binding energy and binding energy per nucleon',
      'Apply radioactive decay law and calculate half-life',
      'Distinguish between alpha, beta, and gamma decay',
      'Explain nuclear fission and fusion reactions',
    ],
    keyFormulas: ['E = Δmc²', 'N = N₀e^(-λt)', 't½ = 0.693/λ'],
    difficulty: 'Medium',
    studyTimeMinutes: 80,
  },
  {
    subjectId: 'physics',
    chapterId: 14,
    name: 'Semiconductor Electronics',
    unit: 'Semiconductors',
    topics: [
      'p-n Junction',
      'Diode',
      'Zener Diode',
      'Transistor',
      'Logic Gates',
      'Rectifier',
    ],
    overview:
      'Covers semiconductor physics, p-n junction diodes, Zener diodes, transistors, and basic logic gates.',
    objectives: [
      'Distinguish between conductors, semiconductors, and insulators',
      'Explain the working of p-n junction in forward and reverse bias',
      'Analyse transistor as a switch and amplifier',
      'Construct truth tables for basic logic gates',
    ],
    keyFormulas: ['IE = IB + IC', 'β = IC/IB', 'VCC = ICRC + VCE'],
    difficulty: 'Medium',
    studyTimeMinutes: 85,
  },
  {
    subjectId: 'chemistry',
    chapterId: 1,
    name: 'Solutions',
    unit: 'Physical',
    topics: [
      'Molarity',
      'Molality',
      "Raoult's Law",
      'Colligative Properties',
      "Van't Hoff Factor",
      'Osmotic Pressure',
    ],
    overview:
      "Studies types of solutions, concentration terms, and colligative properties. Raoult's law and Van't Hoff factor are central to understanding solution behaviour.",
    objectives: [
      'Express concentration in molarity, molality, and mole fraction',
      "Apply Raoult's law to ideal and non-ideal solutions",
      'Calculate colligative properties: elevation of boiling point, depression of freezing point',
      "Use Van't Hoff factor for electrolyte solutions",
    ],
    keyFormulas: ['ΔTb = Kb·m', 'ΔTf = Kf·m', 'π = iMRT'],
    difficulty: 'Medium',
    studyTimeMinutes: 80,
  },
  {
    subjectId: 'chemistry',
    chapterId: 2,
    name: 'Electrochemistry',
    unit: 'Physical',
    topics: [
      'Galvanic Cell',
      'Nernst Equation',
      'Electrolysis',
      "Kohlrausch's Law",
      'Corrosion',
      'Conductance',
    ],
    overview:
      "Covers electrochemical cells, electrode potentials, Nernst equation, electrolysis, and corrosion. Kohlrausch's law relates conductance to concentration.",
    objectives: [
      'Distinguish between galvanic and electrolytic cells',
      'Apply Nernst equation to calculate cell potential',
      "Use Kohlrausch's law for molar conductivity",
      'Explain the mechanism of corrosion and its prevention',
    ],
    keyFormulas: ['E = E° - (RT/nF)lnQ', 'ΛM = ΛM° - K√C', 'ΔG° = -nFE°'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'chemistry',
    chapterId: 3,
    name: 'Chemical Kinetics',
    unit: 'Physical',
    topics: [
      'Rate of Reaction',
      'Order of Reaction',
      'Arrhenius Equation',
      'Half Life',
      'Activation Energy',
      'Rate Law',
    ],
    overview:
      'Studies the rate of chemical reactions, factors affecting rate, rate laws, and the Arrhenius equation. Covers integrated rate equations for zero and first order reactions.',
    objectives: [
      'Define rate of reaction and rate constant',
      'Derive integrated rate equations for zero and first order reactions',
      'Apply Arrhenius equation to calculate activation energy',
      'Distinguish between molecularity and order of reaction',
    ],
    keyFormulas: ['r = k[A]ⁿ', 'k = Ae^(-Ea/RT)', 't½ = 0.693/k'],
    difficulty: 'Hard',
    studyTimeMinutes: 90,
  },
  {
    subjectId: 'chemistry',
    chapterId: 4,
    name: 'Surface Chemistry',
    unit: 'Physical',
    topics: [
      'Adsorption',
      'Colloids',
      'Emulsions',
      'Catalysis',
      'Tyndall Effect',
      'Brownian Motion',
    ],
    overview:
      'Covers adsorption, colloids, emulsions, and catalysis. Explains the Tyndall effect, Brownian motion, and the distinction between lyophilic and lyophobic colloids.',
    objectives: [
      'Distinguish between adsorption and absorption',
      'Explain Freundlich and Langmuir adsorption isotherms',
      'Describe properties of colloids and emulsions',
      'Explain homogeneous and heterogeneous catalysis',
    ],
    keyFormulas: ['x/m = kp^(1/n)', 'θ = ap/(1+ap)'],
    difficulty: 'Easy',
    studyTimeMinutes: 60,
  },
  {
    subjectId: 'chemistry',
    chapterId: 5,
    name: 'p-Block Elements',
    unit: 'Inorganic',
    topics: [
      'Group 15 Elements',
      'Group 16 Elements',
      'Group 17 Elements',
      'Group 18 Elements',
      'Ozone',
      'Oxoacids',
    ],
    overview:
      'Covers the chemistry of p-block elements in groups 15–18. Includes preparation, properties, and uses of important compounds like ammonia, sulphuric acid, and halogens.',
    objectives: [
      'Describe trends in properties of group 15, 16, 17, and 18 elements',
      'Explain preparation and properties of NH₃, HNO₃, H₂SO₄, and HCl',
      'Compare oxidising power of halogens',
      'Explain the anomalous behaviour of nitrogen and oxygen',
    ],
    keyFormulas: [],
    difficulty: 'Hard',
    studyTimeMinutes: 110,
  },
  {
    subjectId: 'chemistry',
    chapterId: 6,
    name: 'd- and f-Block Elements',
    unit: 'Inorganic',
    topics: [
      'Transition Metals',
      'Lanthanides',
      'Actinides',
      'Oxidation States',
      'Catalytic Properties',
      'Interstitial Compounds',
    ],
    overview:
      'Studies transition metals and inner transition metals (lanthanides and actinides). Covers variable oxidation states, coloured compounds, and catalytic properties.',
    objectives: [
      'Explain variable oxidation states of transition metals',
      'Describe the preparation and properties of KMnO₄ and K₂Cr₂O₇',
      'Compare properties of lanthanides and actinides',
      'Explain catalytic and magnetic properties of transition metals',
    ],
    keyFormulas: [],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'chemistry',
    chapterId: 7,
    name: 'Coordination Compounds',
    unit: 'Inorganic',
    topics: [
      'Ligands',
      'IUPAC Nomenclature',
      'Isomerism',
      'Crystal Field Theory',
      'Stability',
      'Bonding',
    ],
    overview:
      'Covers coordination compounds, IUPAC nomenclature, isomerism, bonding theories (VBT and CFT), and stability of complexes.',
    objectives: [
      'Apply IUPAC rules to name coordination compounds',
      'Identify and explain types of isomerism in complexes',
      'Apply Crystal Field Theory to explain colour and magnetism',
      'Calculate stability constants of coordination compounds',
    ],
    keyFormulas: ['Δ₀ = hν'],
    difficulty: 'Hard',
    studyTimeMinutes: 100,
  },
  {
    subjectId: 'chemistry',
    chapterId: 8,
    name: 'Haloalkanes and Haloarenes',
    unit: 'Organic',
    topics: [
      'SN1 Reaction',
      'SN2 Reaction',
      'Elimination',
      'Grignard Reagent',
      'Aryl Halides',
      'Optical Isomerism',
    ],
    overview:
      'Covers nomenclature, preparation, and reactions of haloalkanes and haloarenes. Includes SN1, SN2, and elimination reactions, and the Grignard reagent.',
    objectives: [
      'Name haloalkanes and haloarenes by IUPAC system',
      'Distinguish between SN1 and SN2 mechanisms',
      'Explain the preparation and reactions of Grignard reagent',
      'Compare reactivity of haloalkanes and haloarenes',
    ],
    keyFormulas: [],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'chemistry',
    chapterId: 9,
    name: 'Alcohols, Phenols and Ethers',
    unit: 'Organic',
    topics: [
      'Preparation of Alcohols',
      'Reactions of Phenols',
      'Williamson Synthesis',
      'Acidity',
      'Oxidation',
      'Lucas Test',
    ],
    overview:
      'Studies the preparation, physical and chemical properties of alcohols, phenols, and ethers. Covers acidity, oxidation reactions, and Williamson synthesis.',
    objectives: [
      'Prepare alcohols and phenols from various precursors',
      'Compare acidity of alcohols and phenols',
      'Explain Williamson synthesis of ethers',
      'Describe oxidation reactions of primary, secondary, and tertiary alcohols',
    ],
    keyFormulas: [],
    difficulty: 'Medium',
    studyTimeMinutes: 85,
  },
  {
    subjectId: 'chemistry',
    chapterId: 10,
    name: 'Aldehydes, Ketones and Carboxylic Acids',
    unit: 'Organic',
    topics: [
      'Nucleophilic Addition',
      'Aldol Condensation',
      'Cannizzaro Reaction',
      'Esterification',
      'Hell-Volhard-Zelinsky',
    ],
    overview:
      'Covers the chemistry of carbonyl compounds and carboxylic acids. Includes nucleophilic addition, aldol condensation, Cannizzaro reaction, and esterification.',
    objectives: [
      'Explain nucleophilic addition to carbonyl compounds',
      'Describe aldol condensation and Cannizzaro reaction',
      'Compare acidity of carboxylic acids',
      'Explain esterification and Hell-Volhard-Zelinsky reaction',
    ],
    keyFormulas: [],
    difficulty: 'Hard',
    studyTimeMinutes: 100,
  },
  {
    subjectId: 'chemistry',
    chapterId: 11,
    name: 'Amines',
    unit: 'Organic',
    topics: [
      'Classification',
      'Basicity',
      'Diazonium Salts',
      'Coupling Reaction',
      'Hofmann Bromamide',
      'Gabriel Synthesis',
    ],
    overview:
      'Studies classification, preparation, and reactions of amines. Covers basicity, diazonium salts, and coupling reactions used in dye synthesis.',
    objectives: [
      'Classify amines as primary, secondary, and tertiary',
      'Compare basicity of aliphatic and aromatic amines',
      'Explain preparation and reactions of diazonium salts',
      'Describe Hofmann bromamide and Gabriel synthesis',
    ],
    keyFormulas: [],
    difficulty: 'Medium',
    studyTimeMinutes: 80,
  },
  {
    subjectId: 'chemistry',
    chapterId: 12,
    name: 'Biomolecules',
    unit: 'Organic',
    topics: [
      'Carbohydrates',
      'Proteins',
      'Enzymes',
      'Nucleic Acids',
      'Vitamins',
      'Hormones',
    ],
    overview:
      'Covers the structure and functions of carbohydrates, proteins, enzymes, nucleic acids, vitamins, and hormones.',
    objectives: [
      'Classify carbohydrates and explain their structures',
      'Describe the structure of proteins and peptide bonds',
      'Explain the role of enzymes as biological catalysts',
      'Describe the structure of DNA and RNA',
    ],
    keyFormulas: [],
    difficulty: 'Easy',
    studyTimeMinutes: 65,
  },
  {
    subjectId: 'chemistry',
    chapterId: 13,
    name: 'Polymers',
    unit: 'Organic',
    topics: [
      'Addition Polymers',
      'Condensation Polymers',
      'Natural Rubber',
      'Nylon',
      'Bakelite',
      'Biodegradable Polymers',
    ],
    overview:
      'Covers classification, preparation, and properties of polymers including addition and condensation polymers, rubber, and biodegradable polymers.',
    objectives: [
      'Classify polymers based on source, structure, and mode of polymerisation',
      'Explain addition and condensation polymerisation mechanisms',
      'Describe properties and uses of nylon, Bakelite, and rubber',
      'Explain biodegradable and non-biodegradable polymers',
    ],
    keyFormulas: [],
    difficulty: 'Easy',
    studyTimeMinutes: 60,
  },
  {
    subjectId: 'chemistry',
    chapterId: 14,
    name: 'Chemistry in Everyday Life',
    unit: 'Organic',
    topics: [
      'Drugs & Medicines',
      'Soaps',
      'Detergents',
      'Food Preservatives',
      'Antacids',
      'Antiseptics',
    ],
    overview:
      'Applies chemistry to everyday life — drugs, soaps, detergents, food additives, and antiseptics. Covers drug-receptor interactions and cleansing action of soaps.',
    objectives: [
      'Classify drugs based on pharmacological effect and target',
      'Explain drug-receptor interaction',
      'Describe the cleansing action of soaps and detergents',
      'Identify common food preservatives, antacids, and antiseptics',
    ],
    keyFormulas: [],
    difficulty: 'Easy',
    studyTimeMinutes: 55,
  },
  {
    subjectId: 'mathematics',
    chapterId: 1,
    name: 'Relations and Functions',
    unit: 'Algebra',
    topics: [
      'Types of Relations',
      'Types of Functions',
      'Composition of Functions',
      'Invertible Functions',
      'Binary Operations',
    ],
    overview:
      'Revisits relations and functions with a focus on types of functions, composition, and invertibility. Introduces binary operations and their properties.',
    objectives: [
      'Identify and classify types of relations and functions',
      'Compute composition of functions and verify associativity',
      'Determine if a function is invertible and find its inverse',
      'Analyse binary operations for commutativity and associativity',
    ],
    keyFormulas: ['(fog)(x) = f(g(x))'],
    difficulty: 'Easy',
    studyTimeMinutes: 60,
  },
  {
    subjectId: 'mathematics',
    chapterId: 2,
    name: 'Inverse Trigonometric Functions',
    unit: 'Algebra',
    topics: [
      'Domain and Range',
      'Principal Values',
      'Properties',
      'Identities',
      'Simplification',
    ],
    overview:
      'Covers inverse trigonometric functions, their domains, ranges, and principal values. Includes important identities and simplification techniques.',
    objectives: [
      'State domain and range of all inverse trig functions',
      'Find principal values of inverse trig expressions',
      'Apply properties and identities to simplify expressions',
      'Prove and use addition formulae for inverse trig functions',
    ],
    keyFormulas: ['sin⁻¹x + cos⁻¹x = π/2', 'tan⁻¹x + cot⁻¹x = π/2'],
    difficulty: 'Medium',
    studyTimeMinutes: 70,
  },
  {
    subjectId: 'mathematics',
    chapterId: 3,
    name: 'Matrices',
    unit: 'Algebra',
    topics: [
      'Types of Matrices',
      'Matrix Operations',
      'Transpose',
      'Symmetric Matrices',
      'Elementary Operations',
    ],
    overview:
      'Covers matrix algebra including types of matrices, operations, transpose, and symmetric/skew-symmetric matrices. Foundation for solving linear systems.',
    objectives: [
      'Perform addition, subtraction, and multiplication of matrices',
      'Find transpose and verify properties of symmetric matrices',
      'Apply elementary row operations',
      'Understand conditions for matrix multiplication',
    ],
    keyFormulas: ['(AB)ᵀ = BᵀAᵀ', '(A+B)ᵀ = Aᵀ+Bᵀ'],
    difficulty: 'Medium',
    studyTimeMinutes: 75,
  },
  {
    subjectId: 'mathematics',
    chapterId: 4,
    name: 'Determinants',
    unit: 'Algebra',
    topics: [
      'Properties of Determinants',
      'Cofactors',
      'Adjoint',
      'Inverse of Matrix',
      "Cramer's Rule",
      'Area of Triangle',
    ],
    overview:
      "Covers determinants, their properties, cofactors, adjoint, and inverse of a matrix. Applications include solving systems of equations using Cramer's rule.",
    objectives: [
      'Evaluate determinants using properties and cofactor expansion',
      'Find adjoint and inverse of a square matrix',
      "Apply Cramer's rule to solve systems of linear equations",
      'Use determinants to find area of triangles',
    ],
    keyFormulas: ['A⁻¹ = adj(A)/|A|', 'Area = ½|det|'],
    difficulty: 'Hard',
    studyTimeMinutes: 90,
  },
  {
    subjectId: 'mathematics',
    chapterId: 5,
    name: 'Continuity and Differentiability',
    unit: 'Calculus',
    topics: [
      'Continuity',
      'Differentiability',
      'Chain Rule',
      'Implicit Differentiation',
      'Logarithmic Differentiation',
      "Rolle's Theorem",
    ],
    overview:
      'Covers continuity and differentiability of functions. Includes chain rule, implicit and logarithmic differentiation, and mean value theorems.',
    objectives: [
      'Test continuity of functions at a point and on an interval',
      'Differentiate composite, implicit, and parametric functions',
      'Apply logarithmic differentiation to complex expressions',
      "State and verify Rolle's and Lagrange's mean value theorems",
    ],
    keyFormulas: ["d/dx[f(g(x))] = f'(g(x))·g'(x)", 'd/dx[ln x] = 1/x'],
    difficulty: 'Hard',
    studyTimeMinutes: 100,
  },
  {
    subjectId: 'mathematics',
    chapterId: 6,
    name: 'Applications of Derivatives',
    unit: 'Calculus',
    topics: [
      'Rate of Change',
      'Increasing & Decreasing',
      'Maxima and Minima',
      'Tangents and Normals',
      'Approximations',
    ],
    overview:
      'Applies derivatives to real-world problems: rate of change, increasing/decreasing functions, tangents, normals, and optimisation.',
    objectives: [
      'Find rate of change of quantities using derivatives',
      'Determine intervals where functions are increasing or decreasing',
      'Find equations of tangents and normals to curves',
      'Solve optimisation problems using first and second derivative tests',
    ],
    keyFormulas: ['slope = dy/dx', 'normal slope = -dx/dy'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'mathematics',
    chapterId: 7,
    name: 'Integrals',
    unit: 'Calculus',
    topics: [
      'Integration by Parts',
      'Substitution',
      'Partial Fractions',
      'Definite Integrals',
      'Properties of Integrals',
    ],
    overview:
      'Covers indefinite and definite integration techniques including substitution, integration by parts, partial fractions, and properties of definite integrals.',
    objectives: [
      'Apply substitution and integration by parts',
      'Decompose rational functions using partial fractions',
      'Evaluate definite integrals using properties',
      'Integrate standard forms and trigonometric functions',
    ],
    keyFormulas: ['∫u dv = uv - ∫v du', '∫₀ᵃ f(x)dx = ∫₀ᵃ f(a-x)dx'],
    difficulty: 'Hard',
    studyTimeMinutes: 110,
  },
  {
    subjectId: 'mathematics',
    chapterId: 8,
    name: 'Applications of Integrals',
    unit: 'Calculus',
    topics: [
      'Area Under Curve',
      'Area Between Curves',
      'Area Using Definite Integrals',
    ],
    overview:
      'Uses definite integration to calculate areas bounded by curves, lines, and axes. Covers area between two curves.',
    objectives: [
      'Set up integrals to find area under a curve',
      'Calculate area between two intersecting curves',
      'Identify limits of integration from graphs',
      'Apply integration to find areas of standard curves',
    ],
    keyFormulas: ['A = ∫ₐᵇ |f(x)| dx'],
    difficulty: 'Medium',
    studyTimeMinutes: 70,
  },
  {
    subjectId: 'mathematics',
    chapterId: 9,
    name: 'Differential Equations',
    unit: 'Calculus',
    topics: [
      'Order and Degree',
      'Variable Separable',
      'Homogeneous DE',
      'Linear DE',
      "Bernoulli's Equation",
    ],
    overview:
      'Covers formation and solution of differential equations. Methods include variable separable, homogeneous, and linear first-order equations.',
    objectives: [
      'Form differential equations by eliminating arbitrary constants',
      'Solve differential equations by variable separable method',
      'Identify and solve homogeneous differential equations',
      'Solve linear first-order differential equations using integrating factor',
    ],
    keyFormulas: ['dy/dx + Py = Q', 'IF = e^∫P dx'],
    difficulty: 'Hard',
    studyTimeMinutes: 90,
  },
  {
    subjectId: 'mathematics',
    chapterId: 10,
    name: 'Vector Algebra',
    unit: 'Vectors & 3D',
    topics: [
      'Types of Vectors',
      'Dot Product',
      'Cross Product',
      'Scalar Triple Product',
      'Projection of Vectors',
    ],
    overview:
      'Covers vector algebra including types of vectors, dot and cross products, and scalar triple product. Applications in geometry and physics.',
    objectives: [
      'Perform addition, subtraction, and scalar multiplication of vectors',
      'Calculate dot product and find angle between vectors',
      'Compute cross product and find area of parallelogram',
      'Evaluate scalar triple product and test coplanarity',
    ],
    keyFormulas: ['a·b = |a||b|cosθ', '|a×b| = |a||b|sinθ'],
    difficulty: 'Medium',
    studyTimeMinutes: 80,
  },
  {
    subjectId: 'mathematics',
    chapterId: 11,
    name: 'Three-Dimensional Geometry',
    unit: 'Vectors & 3D',
    topics: [
      'Direction Cosines',
      'Equation of Line',
      'Equation of Plane',
      'Angle Between Lines',
      'Shortest Distance',
    ],
    overview:
      'Extends 2D coordinate geometry to 3D. Covers direction cosines, equations of lines and planes, and shortest distance between skew lines.',
    objectives: [
      'Find direction cosines and direction ratios of a line',
      'Write equations of lines and planes in vector and Cartesian form',
      'Calculate angle between two lines, two planes, or a line and plane',
      'Find shortest distance between two skew lines',
    ],
    keyFormulas: ['l²+m²+n²=1', 'd = |(b₁×b₂)·(a₂-a₁)|/|b₁×b₂|'],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
  {
    subjectId: 'mathematics',
    chapterId: 12,
    name: 'Linear Programming',
    unit: 'LPP',
    topics: [
      'Feasible Region',
      'Corner Point Method',
      'Maximisation',
      'Minimisation',
      'Graphical Method',
    ],
    overview:
      'Covers formulation and graphical solution of linear programming problems. Includes finding feasible regions and optimal solutions using the corner point method.',
    objectives: [
      'Formulate real-world problems as LPPs',
      'Identify feasible region and corner points graphically',
      'Apply corner point method to find optimal solution',
      'Solve maximisation and minimisation problems',
    ],
    keyFormulas: [],
    difficulty: 'Easy',
    studyTimeMinutes: 60,
  },
  {
    subjectId: 'mathematics',
    chapterId: 13,
    name: 'Probability',
    unit: 'Probability',
    topics: [
      'Conditional Probability',
      "Bayes' Theorem",
      'Random Variables',
      'Binomial Distribution',
      'Mean and Variance',
    ],
    overview:
      "Covers conditional probability, Bayes' theorem, random variables, probability distributions, and the binomial distribution.",
    objectives: [
      'Calculate conditional probability using multiplication theorem',
      "Apply Bayes' theorem to solve inverse probability problems",
      'Define random variables and construct probability distributions',
      'Calculate mean and variance of binomial distribution',
    ],
    keyFormulas: [
      'P(A|B) = P(A∩B)/P(B)',
      'P(Aᵢ|B) = P(Aᵢ)P(B|Aᵢ)/ΣP(Aⱼ)P(B|Aⱼ)',
    ],
    difficulty: 'Hard',
    studyTimeMinutes: 95,
  },
];
